### Handling MIssing Data

In [83]:
import pandas as pd
import numpy as np

In [8]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [9]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [10]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [11]:
string_data[0] = None

In [12]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [13]:
from numpy import nan as NA

In [14]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [15]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [17]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
....: [NA, NA, NA], [NA, 6.5, 3.]])

In [18]:
cleaned = data.dropna()

In [19]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [21]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [23]:
data[4] = NA

In [24]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [25]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [26]:
df = pd.DataFrame(np.random.randn(7, 3))

In [27]:
df.iloc[:4, 1] = NA

In [28]:
df.iloc[:2, 2] = NA

In [29]:
df

0         1         2
0 -0.588127       NaN       NaN
1  0.715115       NaN       NaN
2  0.902204       NaN  0.029841
3 -0.048308       NaN  0.689343
4  1.278276  0.665597  1.531209
5  0.478648 -0.210034 -0.615322
6 -0.282461 -0.580262  1.568552

In [30]:
df.dropna()

0         1         2
4  1.278276  0.665597  1.531209
5  0.478648 -0.210034 -0.615322
6 -0.282461 -0.580262  1.568552

In [37]:
df.dropna(thresh=3)

0         1         2
4  1.278276  0.665597  1.531209
5  0.478648 -0.210034 -0.615322
6 -0.282461 -0.580262  1.568552

In [38]:
df.dropna(thresh=2)

0         1         2
2  0.902204       NaN  0.029841
3 -0.048308       NaN  0.689343
4  1.278276  0.665597  1.531209
5  0.478648 -0.210034 -0.615322
6 -0.282461 -0.580262  1.568552

### Filling In Missing Data

In [39]:
df.fillna(0)

0         1         2
0 -0.588127  0.000000  0.000000
1  0.715115  0.000000  0.000000
2  0.902204  0.000000  0.029841
3 -0.048308  0.000000  0.689343
4  1.278276  0.665597  1.531209
5  0.478648 -0.210034 -0.615322
6 -0.282461 -0.580262  1.568552

In [41]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.588127  0.500000  0.000000
1  0.715115  0.500000  0.000000
2  0.902204  0.500000  0.029841
3 -0.048308  0.500000  0.689343
4  1.278276  0.665597  1.531209
5  0.478648 -0.210034 -0.615322
6 -0.282461 -0.580262  1.568552

In [42]:
_ = df.fillna(0, inplace=True)

In [43]:
df

0         1         2
0 -0.588127  0.000000  0.000000
1  0.715115  0.000000  0.000000
2  0.902204  0.000000  0.029841
3 -0.048308  0.000000  0.689343
4  1.278276  0.665597  1.531209
5  0.478648 -0.210034 -0.615322
6 -0.282461 -0.580262  1.568552

In [44]:
df = pd.DataFrame(np.random.randn(6, 3))

In [45]:
df.iloc[2:, 1] = NA

In [46]:
df.iloc[4:, 2] = NA

In [47]:
df

0         1         2
0  0.594160  0.694202  1.146983
1  0.283253  0.497470  0.987563
2  1.317684       NaN  0.230355
3  1.637898       NaN -0.058421
4  0.919008       NaN       NaN
5  1.172467       NaN       NaN

In [48]:
df.fillna(method='ffill')

0         1         2
0  0.594160  0.694202  1.146983
1  0.283253  0.497470  0.987563
2  1.317684  0.497470  0.230355
3  1.637898  0.497470 -0.058421
4  0.919008  0.497470 -0.058421
5  1.172467  0.497470 -0.058421

In [49]:
df.fillna(method='ffill', limit=2)

0         1         2
0  0.594160  0.694202  1.146983
1  0.283253  0.497470  0.987563
2  1.317684  0.497470  0.230355
3  1.637898  0.497470 -0.058421
4  0.919008       NaN -0.058421
5  1.172467       NaN -0.058421

In [50]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [51]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [52]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

## Data Transformation

### Removing Duplicates

In [4]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3,4, 4]})

In [5]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [6]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [7]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [8]:
data['v1'] = range(7)

In [9]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [10]:
data.drop_duplicates()

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [12]:
data.drop_duplicates(['k1'])          #filter duplicates only based on the 'k1' column

k1  k2  v1
0  one   1   0
1  two   1   1

In [13]:
data.drop_duplicates(['k1', 'k2'], keep = 'last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

In [14]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 
                              'corned beef', 'Bacon', 'pastrami', 'honey ham', 
                              'nova lox'],
                       'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [15]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [16]:
meat_to_animal = {
    'bacon' : 'pig',
    'pulled pork' : 'pig',
    'pastrami' : 'cow',
    'corned beef' : 'cow',
    'honey ham' : 'pig',
    'nova lox' : 'salmon'
}

In [17]:
lowercased = data['food'].str.lower()

In [18]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [19]:
data['animal'] = lowercased.map(meat_to_animal)

In [20]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [21]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Replacing Values 

In [22]:
data = pd.Series([1., -999., 2., -999., -1000, 3.])

In [23]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [24]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [25]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [26]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis Indexes

In [27]:
data = pd.DataFrame(np.arange(12).reshape(3, 4),
                   index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [28]:
transform = lambda x: x[:4].upper()

In [29]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [30]:
data.index = data.index.map(transform)

In [31]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [32]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [33]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekboo'})

one  two  peekboo  four
INDIANA    0    1        2     3
COLO       4    5        6     7
NEW        8    9       10    11

In [34]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [35]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### Discretization and Binning

In [37]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [38]:
bins = [18, 25, 35, 60, 100]

In [39]:
cats = pd.cut(ages, bins)

In [40]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [41]:
cats.codes            #array form of categories


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [42]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [43]:
pd.value_counts(cats)                    #bin counts for the result of pandas.cut

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [44]:
pd.cut(ages, [18,26, 36, 61, 100], right=False)         #now right limit is open and left is close

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [45]:
group_names = ['Youth', 'YoungAdult', 'MiddleAge', 'Senior']

In [46]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAge, MiddleAge, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAge < Senior]

In [47]:
data = np.random.rand(20)

In [48]:
data

array([0.63258523, 0.37594048, 0.38405485, 0.49470651, 0.14354534,
       0.92859388, 0.20230361, 0.11846986, 0.21543609, 0.25650837,
       0.3685431 , 0.67142752, 0.8851634 , 0.10135736, 0.52275175,
       0.47319143, 0.20937846, 0.02985864, 0.2536373 , 0.89608039])

In [49]:
pd.cut(data, 4, precision=2)

[(0.48, 0.7], (0.25, 0.48], (0.25, 0.48], (0.48, 0.7], (0.029, 0.25], ..., (0.25, 0.48], (0.029, 0.25], (0.029, 0.25], (0.029, 0.25], (0.7, 0.93]]
Length: 20
Categories (4, interval[float64]): [(0.029, 0.25] < (0.25, 0.48] < (0.48, 0.7] < (0.7, 0.93]]

In [51]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [53]:
data = np.random.rand(1000)

In [54]:
pd.qcut(data, 4)

[(0.747, 1.0], (-0.000759, 0.238], (0.238, 0.515], (0.515, 0.747], (0.515, 0.747], ..., (0.515, 0.747], (-0.000759, 0.238], (-0.000759, 0.238], (0.747, 1.0], (0.515, 0.747]]
Length: 1000
Categories (4, interval[float64]): [(-0.000759, 0.238] < (0.238, 0.515] < (0.515, 0.747] < (0.747, 1.0]]

In [55]:
pd.value_counts(pd.qcut(data, 4))

(0.747, 1.0]          250
(0.515, 0.747]        250
(0.238, 0.515]        250
(-0.000759, 0.238]    250
dtype: int64

In [56]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(0.515, 0.9], (0.107, 0.515], (0.107, 0.515], (0.515, 0.9], (0.515, 0.9], ..., (0.515, 0.9], (0.107, 0.515], (0.107, 0.515], (0.515, 0.9], (0.515, 0.9]]
Length: 1000
Categories (4, interval[float64]): [(-0.000759, 0.107] < (0.107, 0.515] < (0.515, 0.9] < (0.9, 1.0]]

### Detecting and Filtering Outlines 

In [57]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [58]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.004508     0.021667    -0.066109    -0.061092
std       0.977843     0.941868     1.017144     1.021039
min      -3.432240    -3.239099    -2.925171    -3.138877
25%      -0.656453    -0.612538    -0.781290    -0.784956
50%      -0.000531     0.020115    -0.036663    -0.058727
75%       0.636939     0.655351     0.637857     0.617408
max       3.089646     3.456019     3.727453     3.025802

In [59]:
col = data[2]

In [60]:
col[np.abs(col) > 3]

636    3.727453
Name: 2, dtype: float64

In [61]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
153 -0.349130 -3.081661  0.465565 -0.120856
414  0.846364  1.431397 -0.465801 -3.138877
502  3.089646 -0.982616 -1.307972  0.843904
536 -0.534393  0.481449 -0.630913  3.025802
588 -0.113575  0.485388  0.711046 -3.007544
631 -1.196312  3.456019 -0.161363 -1.229128
636  0.637741 -0.434773  3.727453 -0.061535
675 -0.000258  3.406980  0.456657  0.648156
890 -3.432240  0.223908  0.094372 -0.037972
990 -0.893094 -3.239099  1.341563 -1.290157

In [62]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [63]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.004166     0.021125    -0.066837    -0.060972
std       0.976140     0.937865     1.014686     1.020530
min      -3.000000    -3.000000    -2.925171    -3.000000
25%      -0.656453    -0.612538    -0.781290    -0.784956
50%      -0.000531     0.020115    -0.036663    -0.058727
75%       0.636939     0.655351     0.637857     0.617408
max       3.000000     3.000000     3.000000     3.000000

In [64]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0  1.0 -1.0
1 -1.0  1.0  1.0  1.0
2  1.0 -1.0  1.0  1.0
3  1.0 -1.0  1.0 -1.0
4  1.0 -1.0 -1.0 -1.0

### Permutation and Random Sampling 

In [65]:
df = pd.DataFrame(np.arange(5*4).reshape(5,4))

In [66]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [67]:
sampler = np.random.permutation(5)

In [70]:
sampler

array([1, 3, 4, 0, 2])

In [71]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11

In [72]:
df.sample(n=3)

0   1   2   3
4  16  17  18  19
1   4   5   6   7
3  12  13  14  15

In [73]:
choices = pd.Series([5, 7, -1, 6, 4])

In [74]:
draws = choices.sample(n=10, replace=True)

In [75]:
draws

1    7
1    7
1    7
4    4
0    5
0    5
3    6
2   -1
4    4
2   -1
dtype: int64

### Computing Indicator/Dummy Variables

If a column in a DataFrame has k distinct values, you would derive a matrix or DataFrame with k columns containing all 1s and 0s.

In [76]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})

In [77]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [78]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [79]:
df_with_dummy = df[['data1']].join(dummies)

In [80]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [ ]:
##### Movielen dataset remaining 


In [81]:
np.random.seed(12345)

In [85]:
values = np.random.rand(10)

In [86]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [87]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [88]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## String Manipulation 

In [89]:
val = 'a,b, guido'

In [90]:
val.split()

['a,b,', 'guido']

In [93]:
pieces = [x.strip() for x in val.split(',')]

In [94]:
pieces

['a', 'b', 'guido']

In [95]:
first, second, third = pieces

In [96]:
first + '::' + second + '::' + third

'a::b::guido'

In [97]:
'guido' in val

True

In [98]:
val.index(',')

1

In [99]:
val.find(':')

-1

In [100]:
val.index(':')

ValueError: substring not found

In [101]:
val.count(',')

2

In [102]:
val.replace(',', '::' )

'a::b:: guido'

In [103]:
val.replace(',', '')

'ab guido'

### Regular Expression

In [104]:
import re

In [105]:
text = "foo   bar\t baz   \tqux"

In [106]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [107]:
regex = re.compile('\s+')

In [108]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [109]:
regex.findall(text)

['   ', '\t ', '   \t']

In [110]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

In [111]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [112]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [113]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [114]:
m = regex.search(text)

In [115]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [117]:
text[m.start():m.end()]

'dave@google.com'

In [118]:
print(regex.match(text))

None


In [119]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [120]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [121]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [122]:
m = regex.match('wesm@bright.net')

In [123]:
m.groups()

('wesm', 'bright', 'net')

In [124]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [125]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



### Vactorized String Functions in Pandas

In [126]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
.....: 'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [127]:
data = pd.Series(data)

In [128]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [129]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [130]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [131]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [132]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [133]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

In [134]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [135]:
matches.str.get(1)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [136]:
matches.str[0]

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [137]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object